image:
  registry: ghcr.io
  name: flaresolverr/flaresolverr
  tag: latest
probes:
  liveness:
    enabled: true
    port: 8191
  startup:
    enabled: true
    port: 8191
ports:
  ClusterIP:
    - port: 8191
