image:
  name: ollama/ollama
env:
  OLLAMA_HOST: 0.0.0.0:80
  OLLAMA_MODELS: /models
probes:
  liveness:
    enabled: true
    port: 80
  startup:
    enabled: true
    port: 80
ports:
  ClusterIP:
  - port: 80
volumes:
  persisted:
  - /models
