defaultUser: ENC[AES256_GCM,data:hUPYP9M=,iv:gaQMYlHRmo5rIVekdIAAtefeRZWOCyFqfeyrc8lb5cQ=,tag:HNPDi+Dcs23ZFZThV6tNFQ==,type:str]
defaultPassword: ENC[AES256_GCM,data:1BISQ0qME2r7gsQJGg==,iv:0lZ20Ep573HpsYTwbL9fYNWZAG3IIDyVJ0IBBkaDxX0=,tag:57QA0508Qct3wjAmJN86ZQ==,type:str]
cloudFlareEmail: ENC[AES256_GCM,data:1/yGYujgMkUiqkbiVc6aNdy89XWH,iv:7kKX5miXfVA1LEYYQslS+udioKrOQsgvVFLcR6Pr/Fg=,tag:PhcGsJgKixZFv3LWcb6qDg==,type:str]
cloudFlareApiKey: ENC[AES256_GCM,data:Bsy/yZQbY2mGrhW9xkdLulCqgtt2XXSzIw5yTdVQZ7pT2O87iQ==,iv:qHSOc2SxglplqptOuoewNOE2dFo12cX6YUcchAM26dg=,tag:5fHJ2J3dpeMbgl6kmpkthg==,type:str]
googleClientId: ENC[AES256_GCM,data:PHXcVbVwLDWip9GyihEGm8VT8y3Wmyp4kDgvT0XsMnyBYewDMZOMWNo3fuWU/Iv32fpTnbQwp9gc8Hu/nbvzVI2xWx8st0Tv,iv:VF5eoSHM7DiyPYHxIG2P6jHvdOKPRoI3eExXuQePkYo=,tag:PaprKe5AsgzXhIM1HDQb9w==,type:str]
googleClientSecret: ENC[AES256_GCM,data:tWxCpahintzsV7rW2EoG6hkE9s2bDJLzoRIt9TKZirrBstA=,iv:rhuWOtF9NqDGCTK+xKBt4rGu2quzHhqf2zAHINZp3pQ=,tag:zrp+jj1aMzCCYZqappt4cg==,type:str]
slackToken: ENC[AES256_GCM,data:13/MQJRydTQiCpRpuojhheU7jfzBnQaw9MSp6L0qXlGpvrb3Lgbjc2dWWBhZIPIA3ip5T0OE4Pc=,iv:+3TdBcMFNi/0oQrBSYObqKP7y2wHiCm17zz7wZBau5k=,tag:4K3DCNmit6KoEbf+ZfVtQg==,type:str]
openApiKey: ENC[AES256_GCM,data:rA1Vrg7bwxfTqLwUmTQM24jBCF+DcTKAu1dVQ8w5YY7TijVayTvuvdkKfWIpKZf7fbhBPywVV1qmEXuSR6As,iv:QOvej8SW4aEk/H61O7tnT5htRFEmA67sDRNUDwk57KI=,tag:SuaSitLENFvc9NooiFF3WQ==,type:str]
sops:
    age:
        - recipient: age1c9tdyzvzg647u0zz8k7u2x55vnw3g5yxghatuw8yl9ql439ku34s8sgc0r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dk03OThiMlR4N3RCNDhX
            SDFLbWMxZjJRQkJIVWM5bm1kOW5uMlFBVFdRClpudWxEbkc3VUNTdlMzUDFmby9K
            RlVXdFJIUkF3enNZOG1hUFNUTUU3eXMKLS0tIFJoNkEyVEpxb3dKM2wzUkE3S1ZG
            bXBRRUtXRndJc0ViZURCNWpFQk1qLzAKdosRjdYAHP2UxjB9ew0/sFHJ2nyAWo/J
            tbnuvc4dgtBXaM7U+qfEas8v9cXwM2+DwSoK+dzEC9f9k3LTjCOhtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-23T14:54:01Z"
    mac: ENC[AES256_GCM,data:ByxCecabEOLV9S9v/Z0cPHQok+AhUKBK9iRNM1t5imM3I1pUaNP4/acqdxRlI2/++4uC/mm1cJeEb5O+vLzvUGok4beA8MPm1MNljHSnyJsMg6TGVs7J8G93ERzSIgr+t+FK6NrrmkED76yWwyA7G/BZG2S2gT8XF8fh9Oqigss=,iv:07wi8kF9IMcmBXqzOuka64wEjMt/LIDt8MsLKsR2tsc=,tag:qHIxin8mnzYXsXKtxOT/kQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
