type: cronjob
schedule: "30 4 * * *"
ttlSecondsAfterFinished: 86400
image:
  name: library/debian
  tag: bookworm-slim
command:
  - /opt/run-backups.sh

volumes:
  claims:
  - claim: nas-persistence-system
    mounts:
      /: /lab/nas/persistence
  - claim: nas-backups-system
    mounts:
      /: /lab/nas/backups
  - claim: pi-backups-system
    mounts:
      /: /lab/pi/backups
      
  config:
  - path: /opt/run-backups.sh
    mode: "0700"
    content: |
      {{ tpl (.Files.Get "configmap/run-backups.sh") . }}
  - path: /opt/.utils.sh
    mode: "0700"
    content: |
      {{ tpl (.Files.Get "configmap/.utils.sh") . }}
  - path: /root/.kube/config
    mode: "0700"
    content: |
      {{ tpl (.Files.Get "configmap/config.kube") . }}

  - path: /opt/persistence/install-dependancies.sh
    mode: "0700"
    content: |
      {{ tpl (.Files.Get "configmap/persistence/install-dependancies.sh") . }}
  - path: /opt/persistence/daily-live-backup.sh
    mode: "0700"
    content: |
      {{ tpl (.Files.Get "configmap/persistence/daily-live-backup.sh") . }}
  - path: /opt/persistence/distribute-latest-daily.sh
    mode: "0700"
    content: |
      {{ tpl (.Files.Get "configmap/persistence/distribute-latest-daily.sh") . }}
