bases:
- ../../config/environments.yaml.gotmpl
- ../../modules/templates.yaml.gotmpl
---
repositories:
- name: keel
  url: https://charts.keel.sh
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: grafana
  url: https://grafana.github.io/helm-charts
---
releases:
- inherit:
  - template: persistenceStorage

- name: backup
  inherit:
  - template: requiresNothing

- name: startpage
  inherit:
  - template: requiresNothing

- name: keel
  inherit:
  - template: requiresNothing
  values: [keel/values.yaml.gotmpl]

# this storage is required as prometheus creates it own pvc
- name: prometheus-persistence
  inherit:
  - template: storage
  values:
  - unclaimed: true
    nfs:
      path: "{{ .Values.persistencePath }}/{{ .Release.Namespace }}/prometheus"

- name: prometheus
  inherit:
  - template: requiresPersistence
  values: [prometheus/values.yaml.gotmpl]
  needs: [prometheus-persistence]

- name: loki
  inherit:
  - template: requiresPersistence
  values: [loki/values.yaml.gotmpl]