bases:
- ../../config/environments.yaml.gotmpl
- ../../modules/templates.yaml.gotmpl
---
repositories:
- name: traefik
  url: https://traefik.github.io/charts
---
releases:
- inherit:
  - template: deployment-storage

- name: proxy
  inherit:
  - template: stateless-deployment

- name: whoami
  inherit:
  - template: stateful-deployment

- name: speedtest
  inherit:
  - template: stateful-deployment

- name: smokeping
  inherit:
  - template: stateful-deployment

# { {- if .Values.isLive }}
- name: ip-updater
  inherit:
  - template: stateful-deployment

- name: traefik-forward-auth
  inherit:
  - template: stateful-deployment
  needs:
  - traefik
# { {- end }}

- name: traefik
  inherit:
  - template: stateful-deployment
  values: [traefik/values.yaml.gotmpl]