image:
  name: linuxserver/nextcloud
  tag: latest
ports:
  ClusterIP:
  - port: 443
    subdomain: files
    https: true
    unprotected: true
volumes:
  persisted:
  - /config
  - /data
security:
  privileged: true