image:
  name: traefik/whoami
  tag: latest
releaseNotes: https://hub.docker.com/r/traefik/whoami/tags
probes:
  liveness:
    enabled: true
    port: 80
  startup:
    enabled: true
    port: 80
ports:
  ClusterIP:
  - port: 80
    subdomain: whoami