image:
  name: linuxserver/chromium
  tag: latest
env:
  DISABLE_IPV6: true
probes:
  liveness:
    enabled: true
    port: 3000
  startup:
    enabled: true
    port: 3000
ports:
  ClusterIP:
    - port: 3000
      subdomain: browser
volumes:
  persisted:
    - /config
gpu:
  enabled: true