image:
  registry: lscr.io
  name: linuxserver/prowlarr
probes:
  liveness:
    enabled: true
  port: 9696
  path: /ping
  startup:
    enabled: true
  port: 9696
  path: /ping
ndots: 2
startpage:
  icon: list
ports:
  ClusterIP:
    - port: 9696
      subdomain: indexer
volumes:
  persisted:
    - /config
