
{{- define "secrets.rendered" -}}
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ tpl (toString $value) $ | b64enc }}
  {{- end }}
{{- end }}

{{- define "components.secrets" -}}

{{- if .Values.secretEnv }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env-{{ include "secrets.rendered" . | toYaml | sha1sum }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-{{ include "secrets.rendered" . | toYaml | sha1sum }}
type: Opaque
immutable: true
data:
  {{ include "secrets.rendered" . }}
{{- end }}

{{- range .Values.volumes.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-vol-{{ (tpl (printf "%s\n%s\n%s" $.Release.Name .path (.content | toYaml)) $) | sha1sum }}
  labels:
    app.kubernetes.io/name: {{ $.Release.Name }}-{{ (tpl (printf "%s\n%s\n%s" $.Release.Name .path (.content | toYaml)) $) | sha1sum }}
type: Opaque
immutable: true
data:
  {{ base .path }}: {{ tpl (toString .content) $ | b64enc }}
{{- end }}

{{- end }}
