{{- define "components.configmap" -}}
{{- range $conf := .Values.volumes.config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helpers.configmap-key" (merge (dict "conf" $conf) $ ) }}
  labels:
    app.kubernetes.io/name: {{ $.Release.Name }}
type: Opaque
immutable: true
data:
  {{- if $conf.content }}
  {{ base .path }}: |{{ tpl $conf.content $ | nindent 4 }}
  {{- else if $conf.dir }}
  {{- range $file, $content := $.Files.Glob (printf "%s/**" .dir) }}
  {{ $file | trimPrefix (printf "%s/" $conf.dir) }}: |{{ $content | toString | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
{{- if and .Values.gpu.enabled (contains "linuxserver/" .Values.image.name) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-linuxserver-gpu
  labels:
    app.kubernetes.io/name: {{ $.Release.Name }}
type: Opaque
immutable: true
data:
  00_gpu-render-group: |{{ include "linuxserver.gpu-render-group" . | nindent 4 }}
{{- end }}
{{- end }}
