bases:
- ../../config/environments.yaml.gotmpl
- ../../modules/templates.yaml.gotmpl
---
releases:
- inherit:
  - template: deployment-storage

- inherit:
  - template: shows-storage
- inherit:
  - template: movies-storage

- name: jellyfin
  inherit:
  - template: stateful-deployment
  - template: use-shows-storage
  - template: use-movies-storage

- name: qbitvpn
  inherit:
  - template: stateful-deployment
  - template: use-shows-storage
  - template: use-movies-storage
