type: daemonset
image:
  registry: ghcr.io
  name: haveagitgat/tdarr_node
  tag: 2.32.01
env:
  serverIP: "{{ .Values.machine_ips.cluster }}"
  serverPort: 8266
  inContainer: true
  ffmpegVersion: 6
fieldEnv:
  nodeName: spec.nodeName
volumes:
  persisted:
  - /app/logs
  - /app/configs
  host:
  - hostPath: /lab/cache/tdarr/shows
    containerPath: /cache/shows
    type: DirectoryOrCreate
  - hostPath: /lab/cache/tdarr/movies
    containerPath: /cache/movies
    type: DirectoryOrCreate
  pvc:
  - claim: "{{ .Values.showsClaim }}"
    mounts:
      library: /library/shows
  - claim: "{{ .Values.moviesClaim }}"
    mounts:
      library: /library/movies
gpu:
  enabled: true
  fix: true
security:
  privileged: true
affinity:
  preferred:
    default: false
  required:
    default: false
    labels:
      affinity/starr.tdarr-client:
        operator: Exists