image:
  registry: lscr.io
  name: linuxserver/code-server
labels:
  backup/skip: 0
  backup/scale.skip: 0
  backup/scale.no-wait: 1
startpage:
  icon: edit-2
env:
  DEFAULT_WORKSPACE: /workspace
  PROXY_DOMAIN: "vs.{{ .Values.domain }}"
secretEnv:
  SUDO_PASSWORD: "{{ .Values.defaultPassword }}"
ports:
  ClusterIP:
    - port: 8443
      subdomain: vs
probes:
  liveness:
    enabled: true
    port: 8443
    delay: 180
    interval: 30
  startup:
    enabled: true
    port: 8443
    delay: 20
    interval: 20
    threshold: 30 # 10 mins
volumes:
  config:
  - path: /custom-cont-init.d
    dir: configmap/custom-cont-init.d
  - path: /static/files
    dir: configmap/static
  secret:
  - path: /static/ssh/id_ed25519
    content: "{{ .Values.private_key | b64dec }}"
    mode: "0600"
  - path: /static/ssh/id_ed25519.pub
    content: "{{ .Values.public_key | b64dec }}"
    mode: "0644"
  persisted:
  - /config
  - /modcache
  pvc:
  - claim: "{{ .Values.workspaceClaim }}"
    mounts:
      /: /workspace
security:
  privileged: true
