# https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
kube-prometheus-stack:
  nameOverride: prometheus
  fullnameOverride: prometheus

  grafana:
    nameOverride: grafana
    fullnameOverride: grafana
    admin:
      existingSecret: grafana-credentials
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
        traefik.ingress.kubernetes.io/router.middlewares: network-x-forwarded-https@kubernetescrd,network-traefik-forward-auth@kubernetescrd
    persistence:
      enabled: true
      type: pvc
      subPath: system/grafana/var/lib/grafana
      existingClaim: persistence-system

  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          metadata:
            name: db
          spec:
            volumeName: prometheus-persistence-system
            selector:
            matchLabels:
              type: prometheus-persistence-system
            accessModes:
            - ReadWriteMany
            resources:
              requests:
                storage: 1Gi

  prometheus-node-exporter:
    nameOverride: node-exporter
    fullnameOverride: node-exporter

  kube-state-metrics:
    nameOverride: kube-state-metrics
    fullnameOverride: kube-state-metrics
