{{- define "components.endpointSlice" -}}
{{- range .Values.proxies }}
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: {{ .name }}-ip4
  labels:
    kubernetes.io/service-name: {{ .name }}
    endpointslice.kubernetes.io/managed-by: manual
addressType: IPv4
endpoints:
- addresses:
  - {{ .ip }}
  conditions:
    ready: true
ports:
  - protocol: TCP
    port: {{ .port }}
{{- end -}}
{{- end -}}