{{- define "components.service" -}}
{{- range .Values.proxies }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app.kubernetes.io/name: {{ .name }}
spec:
  ports:
  - port: {{ .port }}
    targetPort: {{ .port }}
{{- end -}}
{{- end -}}