image:
  registry: lscr.io
  name: linuxserver/sonarr
probes:
  liveness:
    enabled: false
    port: 8989
    path: /ping
  startup:
    enabled: false
    port: 8989
    path: /ping
ndots: 2
startpage:
  icon: tv
ports:
  ClusterIP:
    - port: 8989
      subdomain: shows
volumes:
  persisted:
    - /config
  pvc:
  - claim: "{{ .Values.showsClaim }}"
    mounts:
      library: /library/shows
      downloads: /downloads/shows