---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}
  labels:
    type: {{ .Release.Namespace }}-{{ .Release.Name }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  {{- if .Values.host }}
  hostPath:
    path: {{ .Values.host.path }}
  {{- else }}
  nfs:
{{- $nsSource := get (get .Values.namespace_persistence .Release.Namespace) "source" }}
{{- $server := default $nsSource (.Values.nfs).server | required (printf "missing .Values.nfs.server OR .Values.namespace_persistence.%s.source" .Release.Namespace) }}
    server: {{ tpl $server . }}
    path: {{ tpl ((.Values.nfs).path | default (printf "%s/%s" .Values.persistencePath .Release.Namespace)) . }}
    readOnly: {{ (.Values.nfs).readOnly | default false  }}
  {{- end }}
