{{- if not .Values.unclaimed }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}
spec:
  selector:
    matchLabels:
      type: {{ .Release.Namespace }}-{{ .Release.Name }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
{{- end }}
