# https://openthread.io/guides/border-router/docker/run
# https://www.reddit.com/r/homeassistant/comments/18elri0/has_anyone_had_any_success_with_skyconnects/
image:
  name: openthread/otbr
  tag: latest
args:
- --radio-url
- spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=460800
deploymentStrategy: Recreate
liveness:
  port: 80
ports:
  ClusterIP:
  - port: 80
    subdomain: otbr
  - port: 8081
    name: obtr-api
nameservers:
- 127.0.0.1
volumes:
  host:
  - hostPath: /dev/serial/by-id/usb-Nabu_Casa_Home_Assistant_Connect_ZBT-1_fc6dc2076a39ef1184bd51f454516304-if00-port0
    containerPath: /dev/ttyACM0
    type: CharDevice
security:
  privileged: true
  seccomp: RuntimeDefault
  capabilities:
  - "NET_ADMIN"
  - "SYS_MODULE"
  sysctls:
    net.ipv6.conf.all.disable_ipv6: "0"
    net.ipv4.conf.all.forwarding: "1"
    net.ipv6.conf.all.forwarding: "1"
